#!/bin/bash
apt-get -y install fping &&\
sh -c "fping proxy && echo 'Acquire { Retries \"0\"; HTTP { Proxy \"http://proxy:3128\";}; };' > /etc/apt/apt.conf.d/40proxy || true" &&\
apt-get -y update &&\
apt-get -y install software-properties-common &&\
add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe" &&\
add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates main universe" &&\
apt-get -y update &&\
apt-mark hold initscripts &&\
apt-get -y upgrade &&\
echo "Asia\Bangkok" >> /etc/timezone &&\
echo "export LANGUAGE=en_US.UTF-8" >> /etc/bash.bashrc &&\
echo "export LANG=en_US.UTF-8" >> /etc/bash.bashrc &&\
echo "export LC_ALL=en_US.UTF-8" >> /etc/bash.bashrc &&\
export LANGUAGE=en_US.UTF-8 &&\
export LANG=en_US.UTF-8 &&\
export LC_ALL=en_US.UTF-8 &&\
locale-gen en_US.UTF-8 &&\
dpkg-reconfigure locales &&\
add-apt-repository -y ppa:rwky/redis &&\
add-apt-repository -y ppa:nginx/stable &&\
apt-get install -y curl && curl http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | apt-key add - &&\
echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" | \
tee /etc/apt/sources.list.d/postgres.list &&\
apt-get -y update &&\
apt-get -y install build-essential git curl wget \
                   libxslt-dev libcurl4-openssl-dev \
                   libssl-dev libyaml-dev libtool \
                   libxml2-dev gawk \
                   pngcrush imagemagick \
                   postgresql-9.3 postgresql-client-9.3 \
                   postgresql-contrib-9.3 libpq-dev libreadline-dev \
                   nginx language-pack-en sudo cron \
                   psmisc rsyslog &&\
dpkg-divert --local --rename --add /sbin/initctl &&\
sh -c "test -f /sbin/initctl || ln -s /bin/true /sbin/initctl" &&\
mkdir /tmp/redis_install &&\
  cd /tmp/redis_install &&\
  wget http://redis.googlecode.com/files/redis-2.6.7.tar.gz &&\
  tar xvf redis-2.6.7.tar.gz &&\
  cd redis-2.6.7 &&\
  make &&\
  make install &&\
  cd utils &&\
  ./install_server.sh &&\
  rm -rf /tmp/redis_install &&\
apt-get -y install haproxy openssh-server &&\
echo 'gem: --no-document' >> /usr/local/etc/gemrc &&\
mkdir /src && cd /src && git clone https://github.com/sstephenson/ruby-build.git &&\
cd /src/ruby-build && ./install.sh &&\
cd / && rm -rf /src/ruby-build && ruby-build 2.0.0-p481 /usr/local &&\
gem update --system &&\
gem install bundler &&\
mkdir /jemalloc && cd /jemalloc &&\
  wget http://www.canonware.com/download/jemalloc/jemalloc-3.4.1.tar.bz2 &&\
  tar -xvjf jemalloc-3.4.1.tar.bz2 && cd jemalloc-3.4.1 && ./configure && make &&\
  mv lib/libjemalloc.so.1 /usr/lib && cd / && rm -rf /jemalloc &&\
apt-get -y install runit monit socat &&\
mkdir -p /etc/runit/1.d &&\
apt-get clean &&\
rm -f /etc/apt/apt.conf.d/40proxy &&\
locale-gen en_US &&
wget http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz &&\
  tar -xvf pngout-20130221-linux.tar.gz &&\
  rm pngout-20130221-linux.tar.gz &&\
  cp pngout-20130221-linux/x86_64/pngout /bin/pngout &&\
  rm -rf pngout-20130221-linux &&\
cat <<EOF >/etc/runit/1
#!/bin/bash

/bin/run-parts --verbose --exit-on-error /etc/runit/1.d
EOF &&\
cat <<EOF >/etc/runit/1.d/cleanup-pids
#!/bin/bash
/bin/echo "Cleaning stale PID files"
/bin/rm -f /var/run/*.pid
EOF &&\
cat <<EOF >/etc/runit/2
#!/bin/bash
/usr/bin/runsvdir -P /etc/service
EOF &&\
useradd discourse -s /bin/bash -m -U &&\
mkdir /var/www && cd /var/www &&\
 git clone https://github.com/discourse/discourse.git &&\
 cd discourse &&\
 git remote set-branches --add origin tests-passed &&\
 cd .. &&\
 chown -R discourse:discourse /var/www/discourse &&\
cd /var/www/discourse &&\
 sudo -u discourse RAILS4=1 bundle install --deployment \
     --without test --without development &&\
cd /var/www/discourse/vendor/bundle &&\
   find . -name tmp -type d | xargs rm -rf && cd / &&\
  wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2 &&\
  tar -xjf phantomjs-1.9.7-linux-x86_64.tar.bz2 &&\
  rm phantomjs-1.9.7-linux-x86_64.tar.bz2 &&\
  cp phantomjs-1.9.7-linux-x86_64/bin/phantomjs /bin/phantomjs &&\
  rm -fr phantomjs-1.9.7-linux-x86_64 &&\
cat <<EOF >/etc/service/cron/run
#!/bin/bash
exec 2>&1
cd /
exec cron -f
EOF &&\
chmod +x /etc/service/cron/run &&\


cd /var/docker/discourse_docker &&\
  pubs templates/dev.cron.template.yml &&\
  pubs templates/dev.syslog.template.yml &&\
  pubs templates/dev.postgres.template.yml &&\
  pubs templates/dev.redis.template.yml &&\
  pubs templates/dev.web.template.yml